// $NAME <$ID@uakron.edu>
//
// ordered.cpp: DO NOT EDIT THIS FILE

#include "ordered_list.hpp"

#include <cassert>
#include <iostream>
#include <vector>

int main() {
  Ordered_list list;

  std::cout << "----------------------------------------------------" << std::endl;
  for (auto x : { 10, 5, 3, 2, 9, 6, 4, 7, 1, 8 })
    list.insert(x);
  list.display();
  assert(list.count() == 10);
  std::cout << "Elements: " << list.count() << std::endl;
  std::cout << "----------------------------------------------------\n" << std::endl;

  std::cout << "----------------------------------------------------" << std::endl;
  for(auto x: { 2, 4, 6, 8, 10 })
    list.remove(x);
  list.display();
  assert(list.count() == 5);
  std::cout << "Elements: " << list.count() << std::endl;
  std::cout << "----------------------------------------------------\n" << std::endl;

  std::cout << "----------------------------------------------------" << std::endl; 
  list.remove(2);
  list.display();
  assert(list.count() == 5);
  std::cout << "Elements: " << list.count() << std::endl;
  std::cout << "----------------------------------------------------\n" << std::endl;

  std::cout << "----------------------------------------------------" << std::endl;
  list.clear();
  list.display();
  assert(list.count() == 0);
  std::cout << "Elements: " << list.count() << std::endl;
  std::cout << "----------------------------------------------------\n" << std::endl;
}
